apiVersion: v1
kind: Pod
metadata:
  name: quarkcm
  namespace: default
spec:
  containers:
  - image: quarkcm:latest
    imagePullPolicy: Always
    name: quarkcm
    volumeMounts:
    - name: quarkcm-volume
      mountPath: /root
  restartPolicy: Always
  volumes:
  - name: quarkcm-volume
    hostPath:
      path: /var
      type: Directory
