// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.8
// source: pkg/grpc/quarkcmsvc.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// QuarkCMServiceClient is the client API for QuarkCMService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuarkCMServiceClient interface {
	// Test
	TestPing(ctx context.Context, in *TestRequestMessage, opts ...grpc.CallOption) (*TestResponseMessage, error)
}

type quarkCMServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQuarkCMServiceClient(cc grpc.ClientConnInterface) QuarkCMServiceClient {
	return &quarkCMServiceClient{cc}
}

func (c *quarkCMServiceClient) TestPing(ctx context.Context, in *TestRequestMessage, opts ...grpc.CallOption) (*TestResponseMessage, error) {
	out := new(TestResponseMessage)
	err := c.cc.Invoke(ctx, "/quarkcmsvc.QuarkCMService/TestPing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuarkCMServiceServer is the server API for QuarkCMService service.
// All implementations must embed UnimplementedQuarkCMServiceServer
// for forward compatibility
type QuarkCMServiceServer interface {
	// Test
	TestPing(context.Context, *TestRequestMessage) (*TestResponseMessage, error)
	mustEmbedUnimplementedQuarkCMServiceServer()
}

// UnimplementedQuarkCMServiceServer must be embedded to have forward compatible implementations.
type UnimplementedQuarkCMServiceServer struct {
}

func (UnimplementedQuarkCMServiceServer) TestPing(context.Context, *TestRequestMessage) (*TestResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestPing not implemented")
}
func (UnimplementedQuarkCMServiceServer) mustEmbedUnimplementedQuarkCMServiceServer() {}

// UnsafeQuarkCMServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuarkCMServiceServer will
// result in compilation errors.
type UnsafeQuarkCMServiceServer interface {
	mustEmbedUnimplementedQuarkCMServiceServer()
}

func RegisterQuarkCMServiceServer(s grpc.ServiceRegistrar, srv QuarkCMServiceServer) {
	s.RegisterService(&QuarkCMService_ServiceDesc, srv)
}

func _QuarkCMService_TestPing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuarkCMServiceServer).TestPing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/quarkcmsvc.QuarkCMService/TestPing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuarkCMServiceServer).TestPing(ctx, req.(*TestRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// QuarkCMService_ServiceDesc is the grpc.ServiceDesc for QuarkCMService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuarkCMService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quarkcmsvc.QuarkCMService",
	HandlerType: (*QuarkCMServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestPing",
			Handler:    _QuarkCMService_TestPing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/grpc/quarkcmsvc.proto",
}
